### ISSUE TITLE
关于文本自动文摘的咨询

### ISSUE THREAD

**Issue by SirWZ** [STHSF/TextRank#10]
关注您的项目两天了，没有搞懂文本自动文摘的结果是如何来的。不清楚哪个类是主入口！
我发现您在AbstractExactor类中有个main方法，但我不清楚您的数据源格式以及Word2Vec 的模型训练情况。还望您解答。

**Comment by STHSF** [comment]
类AbstractExactor中的run函数是主程序入口，main函数类似于测试样例，这段代码里面没有word2vec的训练，仅仅是使用了训练好的word2vec模型，数据源格式与readme中的文章样例一样。

**Comment by SirWZ** [comment]
非常感谢您的回复，我自己训练了一个Word2Vec模型，成功的实现了最终目的！非常感谢。
